add missing include
fix:
```
/build/source/include/colmpc/residual-distance-collision.hxx:64:67: error: 'toFclTransform3f' was not declared in this scope
   64 |   d->r[0] = coal::distance(geom_1.geometry.get(), toFclTransform3f(d->oMg_id_1),
      |                                                   ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```